spring-petclinic/spring-petclinic-rest

pom.xml, readme.md
If Angular developer have Docker installed, it will be easier to run the API backend.
=> Use Google Jib to build and publish a Docker image

src/main/java/org/springframework/samples/petclinic/rest/BindingErrorsResponse.java
=> Fix BindingErrorsResponse to handle null field values

src/main/java/org/springframework/samples/petclinic/rest/RootRestController.java
We had a problem when changing server.servlet.context-path in Spring Boot's configuration. The redirect from / to Swagger UI was no longer working. It should be relative to the current context path instead of a hardcoded value.
=> Fix redirecting / to Swagger UI when context path has been changed

pom.xml, src/test/java/org/springframework/samples/petclinic/service/clinicService/ClinicServiceJdbcTests.java, src/test/java/org/springframework/samples/petclinic/service/clinicService/ClinicServiceJpaTests.java, src/test/java/org/springframework/samples/petclinic/service/clinicService/ClinicServiceSpringDataJpaTests.java, src/test/java/org/springframework/samples/petclinic/service/userService/UserServiceJdbcTests.java, src/test/java/org/springframework/samples/petclinic/service/userService/UserServiceJpaTests.java, src/test/java/org/springframework/samples/petclinic/service/userService/UserServiceSpringDataJpaTests.java
Beginning with Spring Boot 2.3.X-RELEASE the `spring-boot-starter-web` dependency does not depend on the validation starter anymore and hence we need to include the following dependency to use classes from `javax.validation.*`
````xml
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-validation</artifactId>
</dependency>
````
Another necessary change required with Spring Boot 2.3.X is the activation of multiple profiles with the `@ActiveProfiles` annotation. Instead of writing `@ActiveProfiles("p1,p2")` you need to write `@ActiveProfiles({"p1","p2"})`
Migration instructions:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#upgrading-from-spring-boot-22
JUnit 5’s Vintage Engine was removed from …
=> Bump to Spring Boot 2.4.2

src/main/resources/application-mysql.properties, src/main/resources/application-postgresql.properties
I've replaced the deprecated 'spring.datasource.initialize' with the recommended 'spring.datasource.initialization-mode' property. 
> Database Initialization
> Basic DataSource initialization is now only enabled for embedded data sources and will switch off as soon as you’re using a production database. The new `spring.datasource.initialization-mode` (replacing `spring.datasource.initialize`) offers more 
control.
See: 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-database-initialization
=> Replace deprecated property 'spring.datasource.initialize'

pom.xml
JFrog has announced that they are [sunsetting jcenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
Springfox is [also in maven](https://repo1.maven.org/maven2/io/springfox/)...so I don't think this is needed.  It ran fine without for me.
=> Remove jcenter repository

pom.xml, readme.md
This adds `spring-boot-starter-actuator` in order to provide health check and info routes. 
Because `spring-petclinic-rest` is often used as a basic, representative test application, it is often helpful to have a health check to assist in automated deployment environments.  Having a real health check route is preferred over just looking for 200 on a different REST endpoint or checking the swagger UI.  Actuator fits the bill smoothly here!
I also made a note in the README about the two new helpful endpoints.
=> Add spring actuator

pom.xml, src/main/java/org/springframework/samples/petclinic/rest/advice/ExceptionControllerAdvice.java, src/main/java/org/springframework/samples/petclinic/rest/controller/OwnerRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/PetRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/PetTypeRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/SpecialtyRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/UserRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/VetRestController.java, src/main/java/org/springframework/samples/petclinic/rest/controller/VisitRestController.java, src/main/java/org/springframework/samples/petclinic/service/UserService.java, src/main/java/org/springframework/samples/petclinic/service/UserServiceImpl.java, src/main/resources/openapi.yml, src/test/java/org/springframework/samples/petclinic/rest/controller/OwnerRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/PetRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/PetTypeRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/SpecialtyRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/VetRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/VisitRestControllerTests.java
=> Update OpenAPI Spec

readme.md
Add some documentation about the API First Approach in the readme.md file
fix #82 
fix #65
fix #81
=> feat: add documentation for API First approach

src/main/java/org/springframework/samples/petclinic/rest/PetRestController.java
From Documentation:
"APPLICATION_JSON_UTF8_VALUE
Deprecated. as of 5.2 in favor of APPLICATION_JSON_VALUE since major browsers like Chrome now comply with the specification and interpret correctly UTF-8 special characters without requiring a charset=UTF-8 parameter"
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html
=> APPLICATION_JSON_UTF8_VALUE is Deprecated

.github/workflows/maven-build.yml
In our analysis, we observe that the target/site/ directory is generated but not later used during the CI build. Hence, we propose to disable generating this directory to save runtime. The generation of this directory can be disabled by simply adding -Djacoco.skip=true to the mvn command.
=> ignoring unnecessarily generated jacoco report

pom.xml
Without upgrading the Jacoco plugin a mvn install prints out exceptions
=> Update jacoco plugin

src/main/java/org/springframework/samples/petclinic/rest/controller/OwnerRestController.java, src/test/java/org/springframework/samples/petclinic/rest/controller/OwnerRestControllerTests.java
Fix #105
Add an implementation of OwnersRestController#getOwnersPet()
Running integration tests
=> add getOwnersPet implementation

.github/workflows/docker-build.yml, .github/workflows/maven-build.yml, pom.xml, readme.md
Good day!
I created a new workflow to automate building Docker image and publishing it to Docker Hub.
It is also to resolve issue #93, as I noticed the images on Docker Hub are outdated.
I have tested the new workflow in a separate branch during development.
The successful workflow run log can be found at: https://github.com/addianto/spring-petclinic-rest/actions/runs/6611300030/job/17954895176
Please note that the workflow requires two GitHub Secrets (i.e., `DOCKERHUB_USERNAME` & `DOCKERHUB_TOKEN`).
I assume the project's maintainers do have access to the Docker Hub account that publishes the image in order to create the required GitHub Secrets.
=> Build & publish Docker image using GitHub Workflow

pom.xml
Upgrade dependencies to Spring Boot 3.2.1 (and transitively Spring 6.1.2) to make it possible to experiment with Spring's new [Checkpoint/Restore](https://docs.spring.io/spring-framework/reference/integration/checkpoint-restore.html) and [Virtual Threads](https://spring.io/blog/2023/09/09/all-together-now-spring-boot-3-2-graalvm-native-images-java-21-and-virtual/#configuring-a-spring-boot-project-to-use-java-21) support.
=> Upgrade Spring Boot to 3.2.1

pom.xml
Notice that building with JDK 17 and running with JDK 21 (including virtual threads support) works just fine, as long as we don't use virtual threads in our application because the Spring framework is packaged as a multi-release jar file. We only need to build with JDK 21 if we want to use 21 features in our application.
The jacoco upgrade is needed because jacoco tries to instrument some of the JDK classes and the current version 0.8.8 doesn't understand the JDK 21 classs if we are building with JDK 21.
=> Upgrade jacoco to 0.8.11 such that we can build with JDK 21

src/main/java/org/springframework/samples/petclinic/rest/advice/ExceptionControllerAdvice.java, src/main/resources/openapi.yml, src/test/java/org/springframework/samples/petclinic/rest/controller/PetRestControllerTests.java, src/test/java/org/springframework/samples/petclinic/rest/controller/UserRestControllerTests.java
Improved handling of 404 errors for non-existing owners and pets in the `POST /owners/{ownerId}/pets` endpoint. Also switched to using records for error information to simplify and modernize the code.
This PR addresses https://github.com/spring-petclinic/spring-petclinic-rest/issues/130 and enhances both the error handling and the structure of the error responses.
**Changes:**
1. Fixed the endpoint to return a 404 Not Found status for non-existing owners or pets instead of a 400 Bad Request.
2. Refactored error handling by replacing the previous class-based error representation with Java record, which stands for a more concise and immutable way to handle error details.
3. Few test changes, because the old version was wrong
@arey, please review and merge this update.
=> fix: issue130 Return a 404 error while adding a pet to an unexisting owner 

src/main/java/org/springframework/samples/petclinic/service/ClinicServiceImpl.java
This PR makes all fields in the `ClinicServiceImpl` class `final` to ensure they are immutable after initialization. It also removes some redundant imports.
- Made fields in `ClinicServiceImpl` `final`.
- Updated the constructor to initialize these fields.
- Removed unnecessary imports.
- UPD: added private helper method to extract common entity retrieval logic
=> Refactor ClinicServiceImpl

pom.xml, src/main/resources/openapi.yml
Required to fix the ValidationMessage example
=> Bump openapi-generator-maven-plugin from 6.3.0 to 7.8.0

src/main/java/org/springframework/samples/petclinic/security/BasicAuthenticationConfig.java
=> Set up DelegatingPasswordEncoder with NoOpPasswordEncoder

src/main/java/org/springframework/samples/petclinic/mapper/OwnerMapper.java, src/main/java/org/springframework/samples/petclinic/mapper/PetMapper.java, src/main/java/org/springframework/samples/petclinic/mapper/PetTypeMapper.java, src/main/java/org/springframework/samples/petclinic/mapper/UserMapper.java, src/main/java/org/springframework/samples/petclinic/mapper/VetMapper.java, src/main/java/org/springframework/samples/petclinic/mapper/VisitMapper.java
Correcting MapStruct mapping annotations according to the discussions below.
Issue #157
PR #168
PR #173
=> Correcting MapStruct mappings. (issue #157)

src/main/java/org/springframework/samples/petclinic/rest/advice/ExceptionControllerAdvice.java, src/main/resources/openapi.yml
Implements the use of ProblemDetail according to issue #149, separating it from other changes according to PR #173.
=> Implements the use of ProblemDetail for HTTP error responses. (issue #149 and PR #173)

pom.xml
@karianna and @Bragolgirith I remove all maven plugin versions already declared into the inherited `spring-boot-dependencies` parent pom.
=> Fix Java compiler version to 17 and remove duplicated maven plugin versions #194

pom.xml, readme.md, src/main/resources/application.properties
- Added OpenAPI documentation with Swagger UI for API exploration.
- Updated `README.md` to include **detailed API endpoint documentation**.
- Modified `application.properties` to enable OpenAPI.
- Updated `pom.xml` to include OpenAPI dependencies.
- Ensures the project is **fully JMeter-ready** for API load testing.
- Improves API documentation and discoverability.
- Aligns with best practices for **API-first development**.
Related to [issue #198](https://github.com/spring-petclinic/spring-petclinic-rest/issues/198). *Note:* Database schema changes and test dataset improvements (as outlined in [Issue #198](https://github.com/spring-petclinic/spring-petclinic-rest/issues/198)) will be addressed in a separate PR.
=> Ensure API readiness for JMeter testing

src/main/java/org/springframework/samples/petclinic/config/SwaggerConfig.java, terms.txt
This PR replaces the Springfox mention in the Javadoc by the current Swagger UI library in use `springdoc-api`.
It also updates the text inserted into the Info builder and adds some line breaks to the code.
I wonder if you have some URL to set the `termsOfService`?
Seems like it should be a link, not a text.
=> Updates Swagger @Configuration class

readme.md, src/test/jmeter/README.md, src/test/jmeter/petclinic-jmeter-crud-benchmark.jmx
This PR introduces a **JMeter performance test** for benchmarking the **scalability of the Spring PetClinic REST API**. 
- Implements **CRUD performance tests** for **owners**, **pets**, and **visits**.
- Works with the **default database configuration**, ensuring consistency in **local tests**.
- Adds a **README** with clear instructions for running tests and analyzing results.
Notes:
The test supports **configurable parameters** (threads, duration, ramp-up time, operations) for flexibility across different environments.
=> Add JMeter Performance Test for Spring PetClinic REST API

readme.md
Link was broken because of missing context root /petclinic/
=> Added missing context root to h2 console URL

.gitignore, src/main/resources/openapi.yml
This PR updates the validation rules in the OpenAPI spec for OwnerFields and VetFields to ensure proper data validation when creating or updating entities.
- Updated regex patterns for:
- firstName: accepts names with optional hyphens, apostrophes, and spaces.
- lastName: same as above, but allows an optional trailing dot (e.g., "Jr.")
- Ensured all constraints reflect the intended validation logic (minLength, maxLength, pattern).
- Regenerated DTOs accordingly using OpenAPI generator (./mvnw clean compile).
- Manual test with Postman/Swagger to confirm the new validation rules are active.
- Ran ./mvnw verify — all tests pass.
Fixes #148 
---
Let me know if you need any more adjustments. 🚀
=> Extending first and lastname patterns #148

readme.md, src/main/java/org/springframework/samples/petclinic/rest/controller/PetRestController.java, src/main/resources/openapi.yml, src/test/java/org/springframework/samples/petclinic/rest/controller/PetRestControllerTests.java
#139 simplify the API by removing the POST to the /petclinic/api/pets ressource.
=>  Remove the POST endpoint from the /api/pets ressource

pom.xml
This PR updates the `maven-compiler-plugin` configuration to apply MapStruct-specific compiler options only during the main compilation phase. This prevents warnings from appearing during test compilation, where MapStruct is not used.
- Moved MapStruct-related compiler options into an `<execution>` block with `id` set to `default-compile`.
- Ensured the options are applied only during the `compile` phase, not `testCompile`.
- Cleaned up build output by avoiding irrelevant warnings.
- Ran `./mvnw clean verify` — all tests pass.
- Confirmed the warning is no longer present during `testCompile`.
Fixes #187 
---
Let me know if you need any more adjustments. 🚀
=>  Applying MapStruct compiler options only during main compilation

src/main/java/org/springframework/samples/petclinic/rest/controller/OwnerRestController.java, src/test/java/org/springframework/samples/petclinic/rest/controller/OwnerRestControllerTests.java
This PR implements the `updateOwnersPet` method in the `OwnerRestController` class, allowing pet updates for a given owner.
- Validates:
-  Update a pet for a givin owner with success (204 No Content)
- Owner existence (404 if Not Found)
- Pet existence (404 if Not Found)
- Updates the pet’s:
- Name.
- Birthdate.
- Type (if provided and valid)
- Returns `204 No Content` on successful update.
- Integration tests implemented:
- testUpdateOwnersPetSuccess
- testUpdateOwnersPetOwnerNotFound
- testUpdateOwnersPetPetNotFound
- Ran `mvn clean verify` - all tests passed.
Fix #220
=> Adding missing PUT method in OwnerRestController class With Integration Tests

.gitignore, postman-tests.sh, src/test/postman/README.md, src/test/postman/petclinic-nonregressiontests.postman_collection.json
This PR adds a second Postman scenario (02 - Returning Costumer) to our test, refactors the Postman test runner shell script to improve its readability, simplify execution, and ensure environment consistency by checking required dependencies.
- Refactored the shell script to:
- Remove logic that executed each scenario individually.
- Previously, the script ran 1 senario at a time, causing errors and/or inconsistencies with the tests, as well as making repeated calls to newman.
- **Now**, all scenarios are executed once together.
- Improve overall readability and structure.
- Generate a single HTML report instead of one per scenario.
- Automated scenario extraction from the collection file using `jq`.
- Previously, we needed to add each scenarios folder name to the SCENARIOS constant …
=> Adding a second postman scenario, improving & fixing shell script, updating gitignore & postman readme

.github/workflows/newman-pipeline.yml, postman-tests.sh, src/test/postman/petclinic-nonregressiontests.postman_collection.json
This PR adds a CI pipeline that runs our Postman tests via Newman against the PetClinic REST API. On pull‑request events (opened, synchronized, reopened) and manual trigger, the workflow will:
- Launch the PetClinic API
- Wait until the API is reachable
- Execute the Postman collection through Newman
- Generate and upload an HTML report as a build artifact
- New workflow file: `.github/workflows/newman-pipeline.yml` containing:
1.  Checkout Repository (`actions/checkout@v3`)
2. Set up JDK 17 (`actions/setup-java@v4`) 
3. Start PetClinic API (`nohup mvn spring-boot:run &`)
4. Wait for API Availability (polling `http://localhost:9966/petclinic` with timeout)
5. Run Newman Tests by invoking `bash postman-tests.sh`
6. Upload HTML Report (`actions/upload-artifact@v4`, path …
=> Adding CI Workflow to Run Postman Tests with Newman

src/test/java/org/springframework/samples/petclinic/rest/controller/VetRestControllerTests.java
I analyzed the test doubles (mocks) in the test code of the project. In my analysis of the project, I observed that
In tests `testGetVetNotFound` and `testDeleteVetError`:
* The `findVetById` method for the `clinicService` object:
i) is stubbed with argument `-1`
ii) during test execution the method is actually called with argument `999`, resulting in mismatch stubbings
In general, a mismatched stubbing occurs when a method is stubbed with specific arguments in a test but later invoked with different arguments in the code. Mockito recommends addressing this type of issue (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/exceptions/misusing/PotentialStubbingProblem.html).
I propose a solution below to resolve the mismatch stubbing. Happy to modify the pull …
=> Resolved mismatch stubbings in VetRestControllerTests.java

src/test/java/org/springframework/samples/petclinic/rest/controller/PetRestControllerTests.java
I analyzed the test doubles (mocks) in the test code of the project. In my analysis of the project, I observed that
In the test `testGetPetNotFound`:
* The `findPetById` method for the `clinicService` object:
i) is stubbed with argument `-1`
ii) during test execution the method is actually called with argument `999`, resulting in a mismatch stubbing
In general, a mismatched stubbing occurs when a method is stubbed with specific arguments in a test but later invoked with different arguments in the code. Mockito recommends addressing this type of issue (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/exceptions/misusing/PotentialStubbingProblem.html).
I propose a solution below to resolve the mismatch stubbing. Happy to modify the pull request based on …
=> Resolved mismatch stubbings in PetRestControllerTests.java
